### ISSUE TITLE
Recent breakage

### ISSUE THREAD

**Issue by steffleupagus** [1drturtle/avrae-autoupdate#4]
I've been using this for quite some time (thanks for this, by the way, it's been a life saver) and it just recently broke with the following backtrace which seems to point to the requests library failing
```
Traceback (most recent call last):
  File "/app/main.py", line 7, in <module>
    import requests
  File "/app/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/app/urllib3/__init__.py", line 18, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/app/urllib3/connectionpool.py", line 15, in <module>
    from ._request_methods import RequestMethods
  File "/app/urllib3/_request_methods.py", line 10, in <module>
    from .response import BaseHTTPResponse
  File "/app/urllib3/response.py", line 48, in <module>
    from .connection import BaseSSLError, HTTPConnection, HTTPException
  File "/app/urllib3/connection.py", line 24, in <module>
    from .http2 import probe as http2_probe
  File "/app/urllib3/http2/__init__.py", line 3, in <module>
    from importlib.metadata import version
ModuleNotFoundError: No module named 'importlib.metadata'
```
Googling recent requests python library updates seemed to indicate that there were recent changes that might be to blame, but my knowledge of Python is too limited to know how to approach a fix - just thought you might want to be made aware!

**Comment by 1drturtle** [comment]
hi! thanks for the issue request. I've updated the requests library to the latest version. does this work? sorry for the late response, didn't get a notification for the issue.
